name: Demo workflow
on: workflow_dispatch
jobs:
   print:
      runs-on: ubuntu-latest
      steps:
         - name: Print to console
           run: echo "Hello World from Aidana"
         - name: Print my name
           run: your name is Aidana
         
